use_frameworks!

platform :ios, '9.0'

target 'SoNavigationController_Example' do
  pod 'SoNavigationController', :path => '../'

  target 'SoNavigationController_Tests' do
    inherit! :search_paths

    
  end
end
